version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
    ignore:
      # These actions deliver the latest versions by updating the major
      # release tag, so ignore minor and patch versions
      - dependency-name: "actions/*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "Apple-Actions/import-codesign-certs"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
      - dependency-name: "marocchino/sticky-pull-request-comment"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "typescript/js"
    ignore:
      # Ignore major updates to Node.js types, because they need to
      # correspond to the Node.js engine version
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

  - package-ecosystem: "terraform"
    directory: "/examples/templates"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "terraform"
    ignore:
      # We likely want to update this ourselves.
      - dependency-name: "coder/coder"
