apiVersion: v2
name: coder
description: Remote development environments on your infrastructure.
home: https://github.com/coder/coder

# version and appVersion are injected at release.
type: application
version: "0.1.0"
appVersion: "0.1.0"

# Coder has a hard requirement on Kubernetes 1.19, as this version
# introduced the networking.k8s.io/v1 API for the Ingress and
# NetworkPolicy resources.
#
# Additionally, the NOTES.txt file emits a warning if the cluster
# version is outside our soft requirement, in accordance with our
# official support policy.
kubeVersion: ">= 1.19.0-0"

keywords:
  - coder
  - terraform
sources:
  - https://github.com/coder/coder/tree/main/helm
icon: https://helm.coder.com/coder_logo_black.png
maintainers:
  - name: Coder Technologies, Inc.
    email: support@coder.com
    url: https://coder.com/contact
